// ============================
// ملف الترجمة النهائي - Quick Web Tools
// يدعم: الإنجليزية، العربية
// ============================

const translations = {
    // ============================================================
    // اللغة الإنجليزية
    // ============================================================
    en: {
        // ----- الهيدر -----
        site_title: "⚡ Quick Web Tools",
        site_subtitle: "Free tools to solve your daily problems: Stopwatch, AI Text Detection, Video Downloader",

        // ----- شريط التنقل -----
        nav_home: "🏠 Home",
        nav_stopwatch: "⏱️ Stopwatch",
        nav_detector: "🔍 AI Detector",
        nav_downloader: "📥 Downloader",
        nav_blog: "📝 Blog",

        // ----- الصفحة الرئيسية - البطاقات -----
        card_stopwatch_title: "Stopwatch & Timer",
        card_stopwatch_desc: "Set timers or measure time accurately. Perfect for studying, cooking, or exercise.",
        card_stopwatch_btn: "Use Tool →",

        card_detector_title: "AI Text Detector",
        card_detector_desc: "Reviews and comparisons of the best AI text detection tools like ZeroGPT and Copyleaks.",
        card_detector_btn: "Read Review →",

        card_downloader_title: "Video Downloader",
        card_downloader_desc: "A complete guide to the best video download tools from Instagram and YouTube like FastDl.",
        card_downloader_btn: "Read Guide →",

        // ----- محتوى إضافي (الصفحة الرئيسية) -----
        section_title: "📌 Why Micro Web Tools?",
        section_text: "Micro web tools are simple applications that solve one problem quickly and without complexity. In a world full of heavy apps, people look for fast solutions that work directly in the browser.",
        section_features: "⏱️ Stopwatch – Track time precisely for studying, cooking, or sports<br>🔍 AI Detector Reviews – Find the right tool to detect AI-generated text<br>📥 Downloader Guide – Save your favorite videos in high quality",

        // ----- صفحة ساعة الإيقاف -----
        stopwatch_title: "⏱️ Stopwatch - Quick Web Tools",
        stopwatch_subtitle: "Track time accurately with this free online stopwatch",
        stopwatch_start: "▶ Start",
        stopwatch_pause: "⏸ Pause",
        stopwatch_reset: "⟲ Reset",
        stopwatch_lap: "⏱ Lap",
        stopwatch_laps: "📋 Laps",
        stopwatch_no_laps: "No laps recorded yet",
        stopwatch_howto_title: "📌 How to Use the Stopwatch",
        stopwatch_howto_list: "🔹 Click <strong>Start</strong> to begin timing<br>🔹 Click <strong>Lap</strong> to record a lap time without stopping<br>🔹 Click <strong>Pause</strong> to pause the stopwatch<br>🔹 Click <strong>Reset</strong> to reset to zero",
        stopwatch_tips: "💡 <strong>Tip:</strong> Use this stopwatch for studying (Pomodoro technique), cooking, sports training, or any activity that requires precise time tracking.",

        // ----- صفحة كشف النصوص -----
        detector_title: "🔍 AI Text Detector - Quick Web Tools",
        detector_subtitle: "Reviews and comparisons of the best AI text detection tools",
        detector_intro_title: "📌 What Are AI Text Detectors?",
        detector_intro_text: "AI text detectors are tools that analyze text to determine if it was written by a human or generated by artificial intelligence like ChatGPT, Claude, or GPT-4. These tools are essential for educators, content creators, and professionals who need to verify the authenticity of written content.",
        detector_intro_text2: "Below is a comparison of the best AI detection tools available in 2026, including their features, pricing, and accuracy.",
        detector_table_title: "📊 Comparison Table",
        detector_table_tool: "Tool",
        detector_table_accuracy: "Accuracy",
        detector_table_price: "Price",
        detector_table_languages: "Languages",
        detector_table_rating: "Rating",
        detector_table_action: "Visit",
        detector_tips_title: "💡 Tips for Using AI Detectors",
        detector_tips_1: "Test multiple tools – Different detectors may give slightly different results",
        detector_tips_2: "Use longer text – AI detection is more accurate with longer text (200+ words)",
        detector_tips_3: "Check for false positives – Some human-written text may be flagged as AI",
        detector_tips_4: "Combine with plagiarism checkers – For complete content verification",

        // ----- صفحة تحميل الفيديوهات -----
        downloader_title: "📥 Video Downloader - Quick Web Tools",
        downloader_subtitle: "A complete guide to the best video download tools from Instagram, YouTube, and more",
        downloader_tool_title: "📥 Download Videos & Photos",
        downloader_tool_subtitle: "Paste the link from Instagram, YouTube, or TikTok to download content",
        downloader_placeholder: "🔗 Paste Instagram, YouTube, or TikTok link here...",
        downloader_btn: "⬇️ Download",
        downloader_note: "Note: This tool redirects you to the best downloader for your link",
        downloader_intro_title: "📌 What Are Video Downloaders?",
        downloader_intro_text: "Video downloaders are online tools that allow you to save videos, photos, Reels, and Stories from popular social media platforms like Instagram, YouTube, TikTok, and Facebook. These tools are perfect for content creators, educators, and anyone who wants to save their favorite content offline.",
        downloader_intro_text2: "Below is a comparison of the best video download tools available in 2026, including their features, supported platforms, and pricing.",
        downloader_table_title: "📊 Comparison Table",
        downloader_table_tool: "Tool",
        downloader_table_platforms: "Platforms",
        downloader_table_price: "Price",
        downloader_table_quality: "Quality",
        downloader_table_rating: "Rating",
        downloader_table_action: "Visit",
        downloader_tips_title: "💡 Tips for Using Video Downloaders",
        downloader_tips_1: "Check your source – Make sure you have the right to download the content",
        downloader_tips_2: "Choose the right quality – Download in HD for the best viewing experience",
        downloader_tips_3: "Be careful with ads – Some downloader sites may have intrusive ads",
        downloader_tips_4: "Use multiple tools – Different tools may work better for different platforms",
        downloader_tips_5: "Check for file format – MP4 is the most compatible format",

        // ----- الإعلانات -----
        ad_placeholder: "📢 [AdSense Ad will appear here]",

        // ----- الفوتر -----
        footer_text: "All rights reserved © 2026 · Quick Web Tools",
        footer_sub: "QuickTools – Free tools for everyone",
        
        // ----- زر تغيير اللغة -----
        lang_switch: "🌐 العربية"
    },

    // ============================================================
    // اللغة العربية
    // ============================================================
    ar: {
        // ----- الهيدر -----
        site_title: "⚡ أدوات ويب سريعة",
        site_subtitle: "أدوات مجانية لحل مشاكلك اليومية: ساعة إيقاف، كشف النصوص، تحميل الفيديوهات",

        // ----- شريط التنقل -----
        nav_home: "🏠 الرئيسية",
        nav_stopwatch: "⏱️ ساعة الإيقاف",
        nav_detector: "🔍 كشف النصوص",
        nav_downloader: "📥 تحميل فيديوهات",
        nav_blog: "📝 المدونة",

        // ----- الصفحة الرئيسية - البطاقات -----
        card_stopwatch_title: "ساعة الإيقاف والمؤقت",
        card_stopwatch_desc: "ضبط مؤقتات أو قياس الوقت بدقة. مثالية للمذاكرة، الطهي، أو التمارين الرياضية.",
        card_stopwatch_btn: "استخدم الأداة →",

        card_detector_title: "كشف النصوص (AI Detector)",
        card_detector_desc: "مراجعة ومقارنة لأفضل أدوات كشف النصوص المكتوبة بالذكاء الاصطناعي مثل ZeroGPT و Copyleaks.",
        card_detector_btn: "اقرأ المراجعة →",

        card_downloader_title: "تحميل فيديوهات",
        card_downloader_desc: "دليل شامل لأفضل أدوات تحميل الفيديوهات من إنستغرام ويوتيوب مثل FastDl و SaveFrom.",
        card_downloader_btn: "اقرأ الدليل →",

        // ----- محتوى إضافي (الصفحة الرئيسية) -----
        section_title: "📌 لماذا أدوات الويب المصغرة؟",
        section_text: "أدوات الويب المصغرة هي تطبيقات بسيطة تحل مشكلة واحدة بسرعة وبدون تعقيد. في عالم مليء بالتطبيقات الثقيلة، يبحث الناس عن حلول سريعة تعمل مباشرة في المتصفح.",
        section_features: "⏱️ ساعة الإيقاف – لضبط الوقت بدقة للمذاكرة، الطهي، أو الرياضة<br>🔍 مراجعة أدوات كشف النصوص – لمعرفة أي أداة تناسب احتياجاتك<br>📥 دليل تحميل الفيديوهات – لتحميل مقاطعك المفضلة بجودة عالية",

        // ----- صفحة ساعة الإيقاف -----
        stopwatch_title: "⏱️ ساعة الإيقاف - أدوات ويب سريعة",
        stopwatch_subtitle: "تتبع الوقت بدقة مع هذه الساعة المجانية",
        stopwatch_start: "▶ بدء",
        stopwatch_pause: "⏸ إيقاف مؤقت",
        stopwatch_reset: "⟲ إعادة ضبط",
        stopwatch_lap: "⏱ لفة",
        stopwatch_laps: "📋 اللفات",
        stopwatch_no_laps: "لا توجد لفات مسجلة بعد",
        stopwatch_howto_title: "📌 كيفية استخدام ساعة الإيقاف",
        stopwatch_howto_list: "🔹 اضغط <strong>بدء</strong> لبدء العد<br>🔹 اضغط <strong>لفة</strong> لتسجيل لفة دون إيقاف العد<br>🔹 اضغط <strong>إيقاف مؤقت</strong> لإيقاف ساعة الإيقاف مؤقتاً<br>🔹 اضغط <strong>إعادة ضبط</strong> لإعادة العد إلى الصفر",
        stopwatch_tips: "💡 <strong>نصيحة:</strong> استخدم هذه الساعة للمذاكرة (تقنية بومودورو)، الطهي، التمارين الرياضية، أو أي نشاط يتطلب تتبعاً دقيقاً للوقت.",

        // ----- صفحة كشف النصوص -----
        detector_title: "🔍 كشف النصوص - أدوات ويب سريعة",
        detector_subtitle: "مراجعة ومقارنة لأفضل أدوات كشف النصوص",
        detector_intro_title: "📌 ما هي أدوات كشف النصوص؟",
        detector_intro_text: "أدوات كشف النصوص هي أدوات تحلل النص لتحديد ما إذا كان مكتوباً بواسطة إنسان أو تم إنشاؤه بواسطة الذكاء الاصطناعي مثل ChatGPT أو Claude أو GPT-4. هذه الأدوات ضرورية للمعلمين ومنشئي المحتوى والمحترفين الذين يحتاجون إلى التحقق من صحة المحتوى المكتوب.",
        detector_intro_text2: "فيما يلي مقارنة لأفضل أدوات كشف النصوص المتاحة في 2026، بما في ذلك ميزاتها وأسعارها ودقتها.",
        detector_table_title: "📊 جدول المقارنة",
        detector_table_tool: "الأداة",
        detector_table_accuracy: "الدقة",
        detector_table_price: "السعر",
        detector_table_languages: "اللغات",
        detector_table_rating: "التقييم",
        detector_table_action: "زيارة",
        detector_tips_title: "💡 نصائح لاستخدام أدوات كشف النصوص",
        detector_tips_1: "اختبر عدة أدوات – قد تعطي أدوات مختلفة نتائج مختلفة قليلاً",
        detector_tips_2: "استخدم نصوصاً أطول – كشف الذكاء الاصطناعي أكثر دقة مع النصوص الأطول (200+ كلمة)",
        detector_tips_3: "تحقق من النتائج الإيجابية الخاطئة – قد يتم تصنيف بعض النصوص البشرية على أنها ذكاء اصطناعي",
        detector_tips_4: "ادمج مع أدوات كشف الانتحال – للتحقق الكامل من المحتوى",

        // ----- صفحة تحميل الفيديوهات -----
        downloader_title: "📥 تحميل فيديوهات - أدوات ويب سريعة",
        downloader_subtitle: "دليل شامل لأفضل أدوات تحميل الفيديوهات من إنستغرام ويوتيوب والمزيد",
        downloader_tool_title: "📥 تحميل فيديوهات وصور",
        downloader_tool_subtitle: "الصق الرابط من إنستغرام، يوتيوب، أو تيك توك لتحميل المحتوى",
        downloader_placeholder: "🔗 الصق رابط إنستغرام، يوتيوب، أو تيك توك هنا...",
        downloader_btn: "⬇️ تحميل",
        downloader_note: "ملاحظة: هذه الأداة توجهك إلى أفضل محمل لرابطك",
        downloader_intro_title: "📌 ما هي أدوات تحميل الفيديوهات؟",
        downloader_intro_text: "أدوات تحميل الفيديوهات هي أدوات عبر الإنترنت تتيح لك حفظ الفيديوهات والصور وريلز وقصص من منصات التواصل الاجتماعي الشهيرة مثل إنستغرام ويوتيوب وتيك توك وفيسبوك. هذه الأدوات مثالية لمنشئي المحتوى والمعلمين وأي شخص يريد حفظ محتواه المفضل للاستخدام دون اتصال.",
        downloader_intro_text2: "فيما يلي مقارنة لأفضل أدوات تحميل الفيديوهات المتاحة في 2026، بما في ذلك ميزاتها والمنصات المدعومة وأسعارها.",
        downloader_table_title: "📊 جدول المقارنة",
        downloader_table_tool: "الأداة",
        downloader_table_platforms: "المنصات",
        downloader_table_price: "السعر",
        downloader_table_quality: "الجودة",
        downloader_table_rating: "التقييم",
        downloader_table_action: "زيارة",
        downloader_tips_title: "💡 نصائح لاستخدام أدوات تحميل الفيديوهات",
        downloader_tips_1: "تحقق من مصدرك – تأكد من أن لديك الحق في تحميل المحتوى",
        downloader_tips_2: "اختر الجودة المناسبة – حمل بجودة عالية للحصول على أفضل تجربة مشاهدة",
        downloader_tips_3: "كن حذراً مع الإعلانات – قد تحتوي بعض مواقع التحميل على إعلانات مزعجة",
        downloader_tips_4: "استخدم عدة أدوات – قد تعمل أدوات مختلفة بشكل أفضل مع منصات مختلفة",
        downloader_tips_5: "تحقق من تنسيق الملف – MP4 هو التنسيق الأكثر توافقاً",

        // ----- الإعلانات -----
        ad_placeholder: "📢 [سيظهر إعلان AdSense هنا]",

        // ----- الفوتر -----
        footer_text: "جميع الحقوق محفوظة © 2026 · أدوات ويب سريعة",
        footer_sub: "أدوات مجانية للجميع",

        // ----- زر تغيير اللغة -----
        lang_switch: "🌐 English"
    }
};

// ============================================================
// دالة تغيير اللغة
// ============================================================
let currentLang = localStorage.getItem('quicktools_lang') || 'en';

function setLanguage(lang) {
    if (!translations[lang]) return;
    currentLang = lang;
    localStorage.setItem('quicktools_lang', lang);
    updatePageTexts();
    updateDirection(lang);
}

function updatePageTexts() {
    const t = translations[currentLang];
    if (!t) return;

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key] !== undefined) {
            el.innerHTML = t[key];
        }
    });

    const langBtn = document.getElementById('langSwitchBtn');
    if (langBtn) {
        langBtn.textContent = t.lang_switch || '🌐 Switch Language';
    }
}

function updateDirection(lang) {
    const html = document.documentElement;
    if (lang === 'ar') {
        html.setAttribute('dir', 'rtl');
        html.setAttribute('lang', 'ar');
    } else {
        html.setAttribute('dir', 'ltr');
        html.setAttribute('lang', 'en');
    }
}

// تشغيل الترجمة عند تحميل الصفحة
document.addEventListener('DOMContentLoaded', () => {
    // التحقق من معامل اللغة في URL
    const params = new URLSearchParams(window.location.search);
    const langParam = params.get('lang');
    if (langParam && (langParam === 'en' || langParam === 'ar')) {
        setLanguage(langParam);
    } else {
        updatePageTexts();
        updateDirection(currentLang);
    }
});
